---

#- name: set hostname
#use templates
#



- name : pull zahite-seed
  become: yes
  become_user: solo
  git:
    repo: https://github.com/satiku/seed
    dest: /home/solo/zahite-seed


- lineinfile:
        create: yes 
        dest: /home/solo/zahite-seed/Docker/COMPOSE/WEB-NEXUS-HOTH/.env
        regexp: '^HOST=DEV1'
        line : 'HOST=DEV1'

