
version: '3.2'
services:
  tor:
    build: tor/
    image: tor
    ports:
            - "9050:9050"
    networks:
        net1:
                ipv4_address: 10.5.11.13




networks:
  net1:
    driver: macvlan
    driver_opts:
            parent: eth0
    ipam:
      config:
        - subnet: 10.5.11.0/24
