---

#
# install docker compose 
#
#
#
#


- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: http://archive.itimmer.nl/itimmer.gpg
    state: present


- apt_repository:
    repo: deb http://archive.itimmer.nl/raspbian/moonlight stretch main

    state: present


- name: update apt cache
  apt:
    update_cache: yes
    


- name: install moonlight
  apt: 
    name: moonlight-embedded  
    state: present
  tags: packages

