
version: '3.2'
services:

  varnish:
    image: varnish
    build: ../../Varnish/varnish/
    networks:
      - varnish-haproxy
    depends_on:
      - haproxy
    ports:  
      - "8096:8096"
      - "6082:6082"
#    command: [ "varnishd", "-F", "-a", ":8096", "-T", ":6082", "-b", "haproxy:8096",  "-s", "malloc,512M" ]

  haproxy:
#    image: arm32v7/haproxy:1.9.4
    image: haproxy
    build: ../../HAProxy/haproxy/
    networks:
      - varnish-haproxy
      - haproxy-jellyfin
    depends_on:
      - jellyfin
#    ports:  
#      - "8096:8096"
#    volume:
#      -  /media/archive/gv0/docker_volumes/haproxy/:/usr/local/etc/haproxy 


  jellyfin:
    image: jellyfin/jellyfin:10.2.1-arm
    restart: always
    networks:
      - haproxy-jellyfin
    volumes:
      - type: volume
        source: archive-volume
        target: /mnt/library
        volume:
          nocopy: true
      - type: volume
        source: jellyfin-config-volume
        target: /config
        volume:
          nocopy: true
      - type: volume
        source: jellyfin-cache-volume
        target: /cache
        volume:
          nocopy: true

#    ports:  
#      - "8096:8096"





volumes:
  archive-volume:
    driver_opts:
      type: "nfs"
      o: "addr=10.5.11.20,nolock,soft,rw"
      device: ":/export/Archive"
  jellyfin-config-volume:
    driver_opts:
      type: "nfs"
      o: "addr=10.5.11.20,nolock,soft,rw"
      device: ":/export/Volumes/$HOST/WEB-NEXUS-HOTH/jellyfin/config"
  jellyfin-cache-volume:
    driver_opts:
      type: "nfs"
      o: "addr=10.5.11.20,nolock,soft,rw"
      device: ":/export/Volumes/$HOST/WEB-NEXUS-HOTH/jellyfin/cache"





networks:
  haproxy-jellyfin:
    driver: overlay
    attachable: true
  varnish-haproxy:
    driver: overlay
    attachable: true

