
version: '3.2'
services:

  varnish:
    image: varnish
    build: ../../Varnish/varnish/
    networks:
      - varnish-haproxy
    depends_on:
      - haproxy
    ports:  
      - "8096:8096"
      - "6082:6082"
    command: [ "varnishd", "-F", "-a", ":8096", "-T", ":6082", "-b", "haproxy:8096",  "-s", "malloc,512M" ]

  haproxy:
#    image: arm32v7/haproxy:1.9.4
    image: haproxy
    build: ../../HAProxy/haproxy/
    networks:
      - varnish-haproxy
      - haproxy-jellyfin
    depends_on:
      - jellyfin
#    ports:  
#      - "8096:8096"
#    volume:
#      -  /media/archive/gv0/docker_volumes/haproxy/:/usr/local/etc/haproxy 


  jellyfin:
    image: jellyfin/jellyfin:10.2.1-arm
    networks:
      - haproxy-jellyfin
    volumes:
      -  /media/archive/gv0/docker_volumes/jellyfin/config:/config 
      -  /media/archive/gv0/docker_volumes/jellyfin/cache:/cache 
      -  /media/archive/gv0/Archive01/Videos/:/mnt/library
#    ports:  
#      - "8096:8096"






networks:
  haproxy-jellyfin:
    driver: overlay
    attachable: true
  varnish-haproxy:
    driver: overlay
    attachable: true

