---




- name: update apt cache
  apt:
    update_cache: yes
    

- name: install glusterfs-client
  apt: 
    name: glusterfs-client=3.7.6-1ubuntu1
    state: present
  tags: packages




# Mount configuration.
- name: Ensure the Gluster volume is mounted.
  tags: configs
  mount:
    name: /gluster/gvol0
    src: gluster1:/gvol0 
    fstype: glusterfs
    opts: "defaults,_netdev,noauto,x-systemd.automount"
    state: mounted
