---



- name: update apt cache
  apt:
    update_cache: yes
    



- name: install base packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - ntfs-3g
    - minicom
    - vim
    - p7zip-full
    - pv
    - luakit
    - tmux
    - i3


- name: Creates directory
  file: 
    path: /home/pi/tmm
    state: directory



#- name: Unarchive a file that needs to be downloaded (added in 2.0)
#  unarchive:
#    src: http://release.tinymediamanager.org/dist/tmm_2.9.12_597414a_linux.tar.gz
#    dest: /home/pi/tmm
#    remote_src: yes
