---


- name: install haproxy
  apt: name=haproxy state=present update_cache=yes
  tags: packages


- name: copy sources.xml
  copy: src=files/haproxy.cfg dest=/etc/haproxy/haproxy.cfg
  notify: haproxy-reload


- name: enable service httpd and ensure it is not masked
  systemd:
    state: started 
    name: haproxy
    enabled: yes
