---

- name: install base packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - guake
      - ccze


# config.txt teplate
# - name: set config.txt
#   template: src=config.jinja dest=/boot/config.txt
#   notify: reboot


- name: install ansible
  apt:
    name: ansible
    state: present
    update_cache: yes


- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://syncthing.net/release-key.txt
    state: present

- apt_repository:
    repo: deb https://apt.syncthing.net/ syncthing stable
    state: present


- name: install syncthing
  apt:
    name: syncthing=0.14.50
    state: present
    update_cache: yes
  tags: packages
