---
- name: install base packages
  become: true 
  tags: installs
  apt:
    update_cache: yes
    name: "{{ packages }}"
  vars:
    packages:
    - i3  
    - dmenu 
    - i3lock
    - feh
    - xserver-xorg
    - xinit
    - vim-nox
    - compton 
    - lemonbar
    - python-pip 
    - fonts-powerline
    - tmux
    - conky 
    - luakit

- name: install powerline 
  tags: installs
  pip: 
    name: powerline-status



- name: add bar config 
  tags: configs
  copy: 
    src: files/bar.sh
    dest: ~/bar.sh

- name: add bar2 config 
  tags: configs
  copy: 
    src: files/bar2.sh
    dest: ~/bar2.sh

- name: copy background image 
  tags: configs
  copy: 
    src: files/bg.jpg
    dest: ~/bg.jpg


- name: add bash config 
  tags: configs
  copy: 
    src: files/.bashrc
    dest: ~/.bashrc


- name: add i3 config 
  tags: configs
  copy: 
    src: files/config
    dest: ~/.config/i3/config


- name: add vim  config 
  tags: configs
  copy: 
    src: files/.vimrc
    dest: ~/.vimrc

- name: add tmux config 
  tags: configs
  copy: 
    src: files/tmux.conf
    dest: ~/.tmux.conf




 

 
