---


- name: update apt cache
  apt:
    update_cache: yes


- name: install base packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - ntfs-3g
      - minicom
      - vim
      - p7zip-full
      - pv
      - luakit
      - tmux
      - i3


- name: Creates directory
  file:
    path: /home/pi/tmm
    state: directory

- name: copy lightdm config for i3
  copy:
    src: files/lightdm.conf
    dest: /etc/lightdm/lightdm.conf
    owner: root
    group: root
    mode: 0644


- name: set mountpoints
  mount:
    name: /mnt/nfs1/volumes
    src: 10.5.11.20:/export/Volumes/
    fstype: nfs
    state: mounted


- name: set mountpoints
  mount:
    name: /mnt/nfs1/archive
    src: 10.5.11.20:/export/Archive/
    fstype: nfs
    state: mounted


# - name: Unarchive a file that needs to be downloaded (added in 2.0)
#   unarchive:
#     src: http://release.tinymediamanager.org/dist/tmm_2.9.12_597414a_linux.tar.gz
#     dest: /home/pi/tmm
#     remote_src: yes
